(function(root,factory){
  const data=factory();
  if(typeof module==='object'&&module.exports) module.exports=data;
  else root.UGCLibrary=data;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  return {
  "version": "4.0",
  "sourceSummary": {
    "audioHookCount": 404,
    "visualCategoryCount": 12,
    "ctaCount": 86,
    "formatCount": 23
  },
  "audioHooks": {
    "Ganchos De Curiosidade": [
      "Esse produto é muito subestimado no (nicho) _____",
      "\\*como eu não conhecia essa linha antes…",
      "Um produto que uso todos os dias sem falhar é _____",
      "Minha atual descoberta ______ favorita é esse _____",
      "Vocês vão me odiar quando eu contar isso, mas _____",
      "Você precisa de _____ se for ______ como eu",
      "Eu nunca saio de casa sem ____",
      "4 erros que você está cometendo com ____",
      "Este ____ não tinha o direito de ser tão bom",
      "Eu nunca mais vou ouvir vocês, garotas TikTok",
      "O que a indústria de _____ não quer que você saiba",
      "Odeio dizer isso a você, mas…",
      "Quando você perceber que deveria ter começado a usar (produto), já vai ser tarde demais",
      "Abandonei ____ quando descobri sobre ____",
      "Fiquei com tanto medo de ser enganado com esta compra, mas me arrisquei e posso confirmar 100% que vale a pena",
      "Principais descobertas das minhas compras online:",
      "Quando você AMA se sentir x, mas não tem tempo para x",
      "(Produto) que me fez apaixonar por (nicho) novamente",
      "____ mudou minha vida",
      "Experimente este hack para obter “resultado”",
      "Esta única dica vai mudar sua vida",
      "Nunca mais fico sem ____ durante o____",
      "O jeito mais fácil e prático de ____",
      "Só queria que tivessem me contado isso antes____",
      "Meu ____nunca mais foi o mesmo depois disso aqui",
      "Você não vai acreditar no que eu descobri sobre____",
      "Eu não deveria estar te contando isso____",
      "Só algumas pessoas sabem disso____",
      "Muitas pessoas discordam de mim quando falo isso____",
      "As pessoas vão me odiar por falar isso____",
      "Eles não querem que você saiba disso____",
      "A melhor compra que eu fiz esse ano foi sem dúvidas____",
      "A melhor compra que eu fiz para ____ foi",
      "A melhor compra que no meu ____ foi",
      "Encontrei o ____ perfeito e posso provar",
      "O segredo que ninguém te contou sobre _______",
      "Quer saber como consegui _______?",
      "Este ______ vai surpreender você tanto quanto me surpreendeu",
      "Descubra o que está prestes a acontecer com _______",
      "O que você verá aqui o deixará em estado de choque",
      "Você não vai acreditar no que aconteceu depois de usar _______",
      "Quer ver algo incrível? Este produto ______",
      "Este truque vai deixar você sem palavras ______",
      "Você não vai acreditar no que aconteceu comigo com _______!",
      "(Sim) Quer saber como minha vida mudou com_____?",
      "(Sim) Existe um _______ e eu estou completamente apaixonada",
      "______ é a resposta que você procurava",
      "Este produto ainda não está à venda... pronto para vê-lo?",
      "Você quer saber o que torna _______ único?",
      "Você consegue imaginar como seria (exemplo de vida, cabelo.. perfeito)? Bem, com ____",
      "A espera por um ______ (mágico, perfeito) acabou",
      "Se você quer saber como consegui ______ vou te mostrar",
      "Foi assim que minha vida melhorou quando conheci o…..",
      "Por que ninguém está falando sobre ______?",
      "Por que ninguém está falando sobre isso aqui?",
      "Se você quer conhecer o …… mais vendido de _____",
      "Este produto está sempre esgotado",
      "A busca pelo ______ perfeito acabou",
      "Não consigo mais viver sem esse _____",
      "Meu segredo para melhorar ______",
      "Isso é o que os clientes adoram em ______",
      "Isso vai te deixar sem palavras",
      "Este produto é um viral no",
      "Esta pequena mudança de ____ fez uma grande diferença",
      "A coisa mais especial deste lugar é ____",
      "Também fiquei curioso sobre _____ então vamos experimentar",
      "A história desta marca me surpreendeu",
      "Economizei 3 meses para _____ e valeu a pena",
      "Isso vai te emocionar tanto quanto me emocionou",
      "É por isso que minha visão sobre _____ mudou",
      "Isto é o que acontece quando _____",
      "É por isso que você precisa de _____",
      "Usar _____ é o melhor conselho que já recebi",
      "A maneira mais fácil de ______",
      "Como fiz _____ com ______",
      "Como _____ da maneira mais rápida",
      "A verdade sobre ______",
      "Se você quer ter o melhor ______ vem que eu te conto",
      "Eu não ia compartilhar isso, mas _____",
      "3 coisas que ninguém te conta sobre _____",
      "Prepare-se para ver passar deste ____ para este _____",
      "Achei um ____",
      "Vou te contar como ____",
      "É por isso que eu ____",
      "Isso estava acabando com ____",
      "O segredo para ____",
      "Como multipliquei meus resultados com ____",
      "O que nunca te contaram sobre ____",
      "Como conquistar o ____ sem precisar ____",
      "O segredo por trás de ____",
      "Você tem dificuldades com ____? Então assista isso!",
      "Prepare-se para se surpreender com…",
      "Descubra o ____ que a (pessoa famosa ou referência) usa",
      "Esse é o ____ que a (pessoa famosa ou referência) não fica sem",
      "Meu (estilo) foi de disso para isso",
      "Como meu _____ foi disso, para isso",
      "Você é _____? então isso é para você",
      "Desde que me mostraram esse produto não há como voltar atrás",
      "Tá na hora de _____",
      "Chegou a hora de _____",
      "Esse foi o melhor _____ que eu já fiz",
      "Essa _____ nunca vai te deixar na mão e eu posso provar",
      "Encontrei a _____ mais _____ da internet",
      "Definitivamente viciada em _____",
      "O que era bom, ficou ainda melhor",
      "Transformei o _____ com 1 produto só",
      "Comprei o _____ viral que as maiores influenciadoras usam",
      "Essa loja fez o maior sucesso lá na rede vizinha",
      "Eu não tinha noção de como _____ poderiam transformar tanto a minha _____",
      "Meu maior acerto na _____ foi escolher _____",
      "Quer comprar _____ pagando pouco?",
      "O segredo para comprar _____ com _____ de desconto",
      "A melhor oportunidade para _____ começou",
      "Achadinhos para a minha _____ nessa Black Friday",
      "Alguém aí vai _____ ? em breve",
      "A maioria das _____ não conhecem essa _____ que é Best Seller na _____",
      "Se alguém me perguntasse em qual _____ investir em com certeza diria _____",
      "Ok, fazia um _____ parando a internet",
      "Eu queria que o atendente da _____ tivesse batido na minha porta e me avisado sobre a existência disso aqui"
    ],
    "Ganchos Que Não Parecem Vendas": [
      "Eu estou até com ciúmes desse produto viralizar mas vamos lá",
      "Que eu amo e uso o meu______ para tudo vocês já sabem mas para mim uma das melhores partes é essa…",
      "Esse ______ aqui está dando o que falar porque ele promete um ______e resolvi testar",
      "Já perdi as contas de quantas vezes isso aconteceu comigo e eu só queria que tivessem me apresentado o ______ antes",
      "Essa ______ fez o maior sucesso lá na rede vizinha e _____",
      "A ______ virou o xodó aqui de casa e vou te contar o porquê",
      "Dois produtos que obviamente comprei de novo",
      "A melhor compra que fiz em ____ e muito barata",
      "Sou só eu ou todo mundo também ama ______",
      "Eu não ia dizer que uso ____ mas é bom demais para não compartilhar",
      "Se você sofre de ____ então este _____ é para você amiga",
      "Tomei a melhor decisão usando ______ e aqui está o porquê",
      "Se eu pudesse ter apenas um produto de _____, seria este _____",
      "Lamento não ter comprado isso aqui antes",
      "O melhor presente para ______ (qualquer ocasião)",
      "Pare _______ e tente isso",
      "Coisas em meu ______ que fazem sentido",
      "Todos os meus amigos me perguntam ______",
      "Eu estava tentando isso e UAU _____",
      "Ouvi meus seguidores falando sobre isso e resolvi experimentar também",
      "Passei todo o meu tempo procurando por algo que pudesse (resolver um problema) e me deparei com ___",
      "Não posso deixar de ficar animado toda vez que uso isso",
      "Sinceramente, não tinha grandes expectativas, mas isso me surpreendeu demais",
      "Sabe aquela sensação de quando encontra algo que simplesmente ama?",
      "Cai no marketing da _____ e não me arrependo nem um pouco",
      "Não sei como vivi tanto tempo sem …….",
      "Eu estava procurando algo diferente e este se tornou meu produto favorito",
      "Não quero parecer exagerada, mas isso melhorou completamente minha rotina",
      "Depois de tantas tentativas de produtos, encontrei ouro",
      "Não é só o produto, é toda a experiência",
      "Encontrei isso na rede vizinha e decidi comprar",
      "Você já sabe que eu não minto e aqui está minha opinião sobre esse ____ viral",
      "O melhor disso tudo é que você nem percebe o quanto ____",
      "Não posso mais guardar esse segredo",
      "Venho facilitar a sua vida e por falar nisso de nada",
      "Ok, esse é o meu achado do século",
      "Aqui está meu truque para _____",
      "Não se preocupe, eu também não sabia disso até experimentar",
      "Puramente por acaso",
      "O _____ mais interessante de ______",
      "Você não tem noção de como este produto me faz sentir.",
      "Este produto e eu temos uma conexão literalmente especial.",
      "EU NÃO SABIA que este produto poderia me fazer ______",
      "Há alguns meses fiz isso graças a ______",
      "Há alguns meses experimentei este produto e agradeço a minha eu do passado",
      "Parei de fazer ____ e mudei para ____",
      "Você sabe como é raro encontrar _____?",
      "Não vou a lugares que não usem _____ desta marca",
      "Por que não faço _____ se não for com esta marca",
      "Por que você deve mudar seu _____ normal por um de ______",
      "Nunca faço esse tipo de vídeo mas tenho que recomendar isso para vocês agora",
      "Encontrei ouro... Não encontrei um … tão bom como dessa marca",
      "O ….. (pessoa famosa) pode vir e me dizer para usar outra marca de ____ e eu não farei isso",
      "Sou leal a tudo que esta marca lança e aqui está o porquê",
      "Dizem que os resultados não vêm facilmente, mas com ____ amanhã você os verá",
      "Por ser curioso, agora sou escravo de ____",
      "Todo mundo olha para mim quando ____ e é graças a ____",
      "Meus amigos e eu decidimos comprar _____ para nossa ……. e ____",
      "Eu realmente não gostei de _____ até tentar _____",
      "Achei que não gostava de ____, mas",
      "Em 30 segundos direi por que amo _____ porque estou com pressa",
      "Venho confessar que não uso mais ____ e mudei para ____",
      "Todo mundo está falando sobre produto viral e está perdendo ____",
      "Você sabe que sou fã de ___, então imagine minha empolgação quando descobri:",
      "Eu deveria me sentir culpado por essa obsessão, mas olha isso",
      "Você acredita em mim se eu disser que encontrei ____?",
      "Minha opinião polêmica sobre este famoso produto. \\[...]",
      "Compre tudo isso por R$___ ok? aqui a gente gosta de economizar você sabe",
      "É literalmente muito fácil conseguir ____ com ____",
      "Odeio pessoas que não compartilham seus produtos favoritos, aqui está o meu",
      "Fui para ___ com meu ___ e voltamos com tudo isso",
      "Review de tudo que comprei em ____ por R$____ reais",
      "Você já quis um atalho para ____? Tenho novidades para você",
      "Recebi ___ de ____ e você não sabe o que aconteceu comigo.",
      "Decidi ____ então comecei com ____ desta marca",
      "Você encontra aquelas pessoas que sempre ficam bem com _? É porque eles usam _",
      "Seu conjunto de ___ não está completo sem ___",
      "Achei que ia me arrepender dessa compra, mas zero",
      "Esta é a opção mais barata, mas de melhor qualidade, de ____",
      "Pare o que está fazendo e olhe esse resultado usando ____",
      "Não entendo como isso funciona, mas funciona",
      "Minha amiga, mãe sempre rouba isso do meu armário/bolsa",
      "Eu queria isso desde os ... anos",
      "Investi em ___ e só queria ter feito isso antes",
      "Estou em ____ e é o momento perfeito para recomendar ____",
      "Se você está vendo isso é porque sabe que eu sempre digo a verdade, então",
      "Tenho certeza de que todos nós já passamos por ____",
      "Minha opinião controversa sobre tópico popular é melhor escolher ___",
      "Não sei você, mas esse produto sempre me chamou a atenção",
      "Ninguém me pediu minha opinião sobre ___ mas",
      "Não achei que fosse verdade, mas esse produto me calou",
      "Às vezes, ver-se ___ pode mudar tudo e é por isso que uso ___",
      "Você se lembra do que aconteceu comigo __? Pois bem, já mudei de produto e",
      "As avaliações deste produto são tão boas e não pude deixar de comprar",
      "Eu sei que você também quer ter ___ foi isso que eu fiz",
      "Ninguém gosta de ___ eu mudei por isso",
      "Você precisa deste hack para ___",
      "Tudo o que você precisa saber sobre __",
      "Economize tempo/dinheiro com ___",
      "Hoje é minha semana ___ usando ___ e veja meus resultados",
      "Este é o melhor ___ e não acredite em mim, acredite em famosos",
      "Você vê como as celebridades têm ___ é porque usam ___",
      "Não posso ser o único procurando por ___",
      "Eu gostaria de saber ___ antes de arruinar meu ___",
      "Ter um ___ perfeito fazia parte da minha lista de desejos",
      "Fiquei traumatizado com esse vídeo, preciso disso agora",
      ". Aposto que você nunca tentou ___ ter ___",
      "Meu pior medo é ___",
      "Você já se perguntou como ___? É graças a ___",
      "Não acredito que isso funciona",
      "Não é por acaso que este produto é viral!",
      "É estupidamente fácil conseguir ___ com ___",
      "Para fazer ___ você tem que ser criativo, experimente este",
      "Garanto resultados como esses com ___",
      "Passei horas pesquisando ___ e já confio em ___",
      "Não sei guardar segredos, então aqui está",
      "Eu não deveria te contar isso, mas ___",
      "Não consigo superar esse ___",
      "Meu namorado ficou bravo comigo porque eu não emprestei ___ para ele",
      "Só sei que Taylor Swift (famoso) compraria isso",
      "Parece ilegal que isso custe apenas R$___",
      "Copie o ___ da celebridade com ___",
      "Eu nasci de novo com este produto",
      "Rodei céu, mar e terra para conseguir ___ e finalmente consegui",
      "De todas as marcas de ___ que experimentei, definitivamente prefiro esta.",
      "Se você começar a usar ___ hoje até ___ em __ semanas, você será uma pessoa diferente",
      "Você quer ter __, mas continua fazendo __, não há como se ajudar. Brincadeira!...",
      "Essa pessoa conseguiu isso em __ dias e eu duvidei",
      "Recuso-me a mudar de marca de ___",
      "Não há nada mais falso do que ___",
      "Isso aconteceu comigo desde o primeiro dia que usei ___",
      "O vício em ___ é real",
      "Se você não sabe ___, você está perdendo",
      "Você não sabe o que está perdendo em ___",
      "Não desperdice seu tempo e dinheiro com ___",
      "Você honestamente acha que isso é real? vamos ver",
      "Não procuro ___ em outras marcas porque já encontrei nesta",
      "Esse produto é ver para crer",
      "Meu conselho para que você tenha ___",
      "O produto viral de ___ está de volta e por pura sorte cheguei lá",
      "Tornei-me um especialista em ___",
      "Mudei de ideia sobre ___ e vou te contar por quê",
      "O universo me enviou um sinal para comprar isto",
      "Recebi um anúncio disso e não resisti",
      "Não subestime o poder deste _____",
      "Se você está procurando ____, já encontrei para você",
      "Os resultados falam por si com _____",
      "Testei as novas _____ da _____ e foi isso que eu descobri"
    ],
    "Ganchos negativos": [
      "Nunca use esse ______ no seu _____ , isso se você quiser continuar com (problemas); caso contrário, esse_____ vai ser seu maior aliado!",
      "Nunca compre esse ______",
      "É melhor você não comprar esse ______",
      "O ______ não é para você, isso se você quiser continuar com (problemas); caso contrário, esse…. vai ser seu maior aliado!",
      "Produtos para o ______ que eu passo longe, porque toda vez que eu passo muito perto, eu faço estoque.",
      "Eu estava errado sobre ______; ele é muito ______ (melhor, etc).",
      "Não caia nessa no marketing da ____ ; você vai ficar viciada igual eu",
      "Esse ______ é muito bom, mas ele tem um sério problema que me arrependi (falar benefícios e no final, adicionar ''arrepender de não ter comprado antes'').",
      "Resolvi testar esse ______ famoso na internet e acho que me arrependi (falar benefícios e no final, adicionar ''arrependi de não ter comprado antes'').",
      "Testei esse ______ e me arrependi ______ de não ter encontrado/comprado antes.",
      "O ______ perfeito não existe; era isso que eu pensava antes de conhecer o ______.",
      "Coisas que eu gostaria de saber antes de comprar o ___ (falar benefícios e como gostaria de ter comprado antes).",
      "Nunca mais eu compro outro ____ na minha vida (porque você encontrou o melhor)."
    ],
    "Ganchos De Solução x Benefício": [
      "Eu disse tchau para _____ e olá para ______",
      "Os benefícios de ______ são de outro mundo",
      "Aumente seu _____ com o poder de _____",
      "A solução que eu procurava sobre _____ está no ______",
      "Isso aqui me ajudou a alcançar _____ super rápido",
      "Quer melhorar seu _____? Eu vou te dar o melhor conselho",
      "Chega de ______, aqui tenho a solução",
      "Você precisa de ____? Eu uso isso para ______",
      "Isso facilitou muito a minha vida",
      "Se você já está cansado de _____ como eu, este produto me ajudou",
      "Você quer se ver _____? este produto fará isso",
      "Os benefícios de ______ são de outro mundo",
      "Aumente seu _____ com o poder de _____",
      "Não subestime o poder deste _____",
      "Facilite sua vida com a ajuda de _____",
      "Vou te contar tudo o que _____ fez por mim",
      "Se você está procurando ____, já encontrei para você",
      "Mudei meus hábitos graças a _____",
      "Mude seus hábitos com a ajuda de ______",
      "Vou te mostrar como _____ fez maravilhas por mim",
      "Este produto tem tudo em um só",
      "Meu dia melhorou quando usei _____",
      "Eu tentei _____ para minha dor _____ e isso mudou minha vida",
      "Não se preocupe mais com _____ com este produto",
      "Diga adeus ao _____, conheça este produto",
      "Me despedi de _____, agora uso _____ e gosto mais",
      "Se você quiser aproveitar _____ eu uso este produto para fazer isso",
      "Esta é minha solução perfeita para ______",
      "Transformei meus _____ problemas em _____",
      "____ fez a diferença na minha vida",
      "____ é a chave para _____",
      "Experimentei a magia dos ______",
      "____ me levou um passo mais perto do meu objetivo em x (tempo)",
      "A solução para ____ estava bem na minha frente",
      "A solução que você procura está bem na sua frente com _____",
      "Subestimei os benefícios de ____, mas fiquei impressionado",
      "_____ e seus benefícios superaram minhas expectativas",
      "Percebi os benefícios de _____ desde o primeiro uso",
      "Os resultados falam por si com _____",
      "Você tem (problema no nicho)?",
      "Minhas 5 coisas favoritas sobre ______"
    ],
    "Ganchos Para Motivar e Inspirar": [
      "Isso é o que você precisa para alcançar seus sonhos/objetivos",
      "Se você está procurando alguma motivação, veja o que me ajudou",
      "Mude sua mentalidade com _______",
      "Como alcancei meus maiores objetivos com ________",
      "______ é a chave para o caminho para o sucesso",
      "Você quer perder o medo de ______? Eu te digo como",
      "Você precisa de um lembrete constante de ___ como eu? Eu recomendo _",
      "Este produto vai fazer você crescer/fortalecer ______",
      "A inspiração se encontra nos lugares mais inesperados, esse é o meu",
      "Com este produto você estará pronto para _____",
      "Encontrei a motivação que você precisa para _____",
      "O poder de ______ vai deixar você em estado de choque, veja isto",
      "_______ vai te mostrar que tudo é possível",
      "Se você está se perguntando como alcançar _____, vou te mostrar _____",
      "Esta é a minha dose diária de motivação para _____",
      "O empurrãozinho que eu precisava para _____foi o _____",
      "Não sei quem precisa ouvir isso, mas este produto _____",
      "A transformação começa com uma decisão, então tome esta",
      "Eu não tinha motivação antes, até descobrir isso",
      "Não deixe ______ te impedir, minha solução foi ______",
      "_____ me inspirou a atingir meu objetivo de _____",
      "Foi assim que consegui passar disso para isso",
      "A força que você precisa para _______ é ______",
      "Não se contente com ______, use ______",
      "Você quer ser uma ______? Eu vou te contar meu segredo",
      "Veja o que você pode conseguir com _______",
      "Pronto para transformar seu _______ disso em aquilo?",
      "Com ______ não há limites",
      "Se você ainda não encontrou o _____ perfeito, não desista.",
      "Direi o que você precisa ouvir de ______",
      "Se eu consegui, você também consegue",
      "Eu determinei e decretei que iria alcançar _____ e consegui com esse",
      "Esse produto tirou minha insegurança em relação a _____",
      "_____ é meu motivo para sorrir",
      "Você é capaz de ______ e eu vou te contar como",
      "Nada me motivou a ______ até conhecer _____",
      "Você quer ver diferença em ______? Eu te digo como",
      "Decidi perseguir meu sonho de _______ e consegui-o por _______"
    ],
    "Ganchos Para Ensinar": [
      "Prometo que esse truque tornou minha vida muito mais fácil.",
      "Estratégias comprovadas para ___",
      "Aprenda a usar _____ em 30 segundos",
      "Como dominar _____ em 30 segundos",
      "Provando como é fácil comprar _____ no site",
      "Eu também não sabia usar ______",
      "Eu te ensino como aprender a usar _____",
      "Você não sabe usar ______? aqui eu te ensino",
      "Aposto que você não sabe sobre _____",
      "Ele sempre me pergunta como visto meu _____",
      "Se você quer ser um especialista em ______ com ______ você pode fazer isso",
      "Como fazer ____ em menos de _____ minutos/dias",
      "Como usar-aproveitar o _____ de 5 maneiras diferentes",
      "Quer aprender como usar _____?",
      "Pov: Aprendi a usar _____ e minha vida mudou",
      "Tornei-me um especialista em ter um ______ e vou te contar como você também pode fazer isso.",
      "Pare _______ e tente fazer isso",
      "Coisas que você não sabia sobre ______",
      "Eu gostaria de saber _____ antes",
      "Não acredito que não sabia disso antes",
      "Não cometa esse erro",
      "Este hack mudou minha vida",
      "A maneira mais fácil de fazer ______",
      "O único _______ que uso para ______",
      "Você não vai acreditar como ______ é simples",
      "Vou te ensinar como _____ de forma eficaz e eficiente _____",
      "Pare de fazer ______ se quiser ter ______",
      "______ você economizará muito tempo",
      "______ você economizará muito dinheiro",
      "Você se sente preso a ______? faça isso",
      "______ não é fácil, mas vou te dar alguns conselhos",
      "Veja por que ______ não está funcionando para você",
      "Isso é o que você precisa saber se for ________",
      "Como tirar o máximo proveito do seu ______",
      "A realidade sobre ______",
      "Minha experiência testando ____ e como fiz isso",
      "Por que você deveria tentar _____?",
      "A coisa mais importante que aprendi usando/consumindo ______",
      "Cometi esse erro para que você não",
      "A melhor maneira de aprender sobre ______",
      "Seus hábitos podem ser mais saudáveis com _____",
      "Meu pior erro e o que aprendi com ele",
      "O _____ mais interessante de _____",
      "Se você é novo no /usando ____ Vou te contar o que fiz quando comecei",
      ". Minha confissão do dia é que nunca aprendi a usar ___ mas já decidi"
    ]
  },
  "visualHooks": {
    "Pegando do céu": {
      "notes": [],
      "references": []
    },
    "ganchos negativos: expressão negativa": {
      "notes": [],
      "references": []
    },
    "Abusar de cores e texturas pois isso é estranhamente satisfatório": {
      "notes": [],
      "references": []
    },
    "Post it": {
      "notes": [],
      "references": [
        "https://youtube.com/shorts/xZNamBNFSuc?feature=share",
        "https://youtube.com/shorts/50iVY5vrq4g?feature=share",
        "https://youtube.com/shorts/BybP6-RQYbg?feature=share",
        "https://youtube.com/shorts/9qMrIpenCOU?feature=share",
        "https://youtube.com/shorts/f4A4RRMEe5A?feature=share",
        "https://youtube.com/shorts/NBlEoG2ptlc?feature=share",
        "https://youtu.be/-V7nKL02oek"
      ]
    },
    "Loop reverso": {
      "notes": [],
      "references": [
        "https://youtube.com/shorts/wfYYuZSDl5E?feature=share",
        "https://youtube.com/shorts/m6N6i2SNo1E?feature=share",
        "https://youtube.com/shorts/EQFN1YmAajk?feature=share",
        "https://youtube.com/shorts/oqCh01IyV30?feature=share",
        "https://youtube.com/shorts/buWiEEXCw7E?feature=share"
      ]
    },
    "Tela verde": {
      "notes": [
        "Caixinha de comentário pode ser feedback do produto, ou falando dos preços, ps: se o comentário tiver emojis, é melhor pois chama atenção."
      ],
      "references": [
        "https://youtube.com/shorts/rTkPq7U0FfE?feature=share",
        "https://youtube.com/shorts/xr8Xe7b1gD4?feature=share",
        "https://youtube.com/shorts/JgqEQ3elhVE?feature=share",
        "https://youtube.com/shorts/fWntO6OYBQY?feature=share",
        "https://youtube.com/shorts/mGKq_xGkIxw?feature=share",
        "https://youtube.com/shorts/uTihFxKpkAo?feature=share",
        "https://youtube.com/shorts/Tilt3xwb6HM?feature=share",
        "https://youtube.com/shorts/1LZECCBHeGA?feature=share",
        "https://youtube.com/shorts/l6YMfu5awG0?feature=share"
      ]
    },
    "Primeira reação": {
      "notes": [],
      "references": [
        "https://youtube.com/shorts/dP5tJSk11B8?feature=share",
        "https://youtube.com/shorts/DRutk2W0jNk?feature=share",
        "https://youtube.com/shorts/e_7bNxWgSa0?feature=share",
        "https://youtube.com/shorts/5Gqqn3R2GW0?feature=share",
        "https://youtube.com/shorts/TwTQqkICo20?feature=share"
      ]
    },
    "Pacote na porta": {
      "notes": [],
      "references": [
        "https://youtube.com/shorts/PqdmQqrtJKc?feature=share",
        "https://youtube.com/shorts/neUD9ZFSnJg?feature=share"
      ]
    },
    "Colocando x tirando câmera": {
      "notes": [],
      "references": [
        "https://youtube.com/shorts/A3FVKfJ7r2A?feature=share",
        "https://youtube.com/shorts/vhDFp4WaqVg?feature=share",
        "https://youtube.com/shorts/GlGb8DTFMps?feature=share",
        "https://youtube.com/shorts/cD6cggN0CV8?feature=share",
        "https://youtube.com/shorts/uaKc-l5ASTo?feature=share",
        "https://youtube.com/shorts/OtCmpadNZlo?feature=share",
        "https://youtu.be/rp6n8gOJ_nI"
      ]
    },
    "Efeito mesa": {
      "notes": [],
      "references": [
        "https://youtube.com/shorts/Re7A-Qr5Y6A?feature=share",
        "https://youtube.com/shorts/swZHoWifB0k?feature=share",
        "https://youtu.be/a_VP_1L373A"
      ]
    },
    "Colocando na cena": {
      "notes": [],
      "references": [
        "https://youtube.com/shorts/xKOzZHblohc?feature=share",
        "https://youtube.com/shorts/S7atG_QhRMc?feature=share",
        "https://youtube.com/shorts/MnPGtYX3a2o?feature=share",
        "https://youtube.com/shorts/QqHLIChowsI?feature=share",
        "https://youtube.com/shorts/phVvijrjpwg?feature=share"
      ]
    },
    "Estralo dedo": {
      "notes": [],
      "references": [
        "https://youtube.com/shorts/XsFF7-EiLwM?feature=share",
        "https://youtube.com/shorts/P3h67SaIeDI?feature=share",
        "https://youtube.com/shorts/OTOUgWBdQ8o?feature=share",
        "https://youtube.com/shorts/8oL-4BnnY8M?feature=share",
        "https://youtube.com/shorts/vqJMpNMj434?feature=share",
        "https://youtube.com/shorts/-MSWKWzLBxY?feature=share",
        "https://youtube.com/shorts/2u28WIjjpkY?feature=share",
        "https://youtube.com/shorts/vBEkr5gBwkM?feature=share",
        "https://youtube.com/shorts/4GoNYiHGAWo?feature=share",
        "https://youtube.com/shorts/Y9fAeYDnBFM?feature=share",
        "https://youtube.com/shorts/n5se4HKFnm8?feature=share",
        "https://youtube.com/shorts/RWpUTox4iVU?feature=share",
        "https://youtube.com/shorts/18wVh9g_fCk?feature=share",
        "https://youtube.com/shorts/b7oZgZPsQW0?feature=share",
        "https://youtube.com/shorts/IaIPYmp1KAc?feature=share"
      ]
    }
  },
  "textualRules": [
    "Legendas harmônicas, fonte, pop-up destacando a palavra-chave."
  ],
  "ctas": {
    "CTA Ads**": [
      "Clique aqui para garantir a sua",
      "E se clicar aqui não botão você ainda garante frete grátis",
      "E tem cupom no site, clica aqui no botão e corre para garantir as suas com desconto",
      "Clique no botão para garantir a sua e me conta o resultado",
      "Eles têm muito mais opções no site, e é só clicar nesse botão aqui para conferir",
      "É muito fácil fazer o pedido, basta clicar aqui",
      "Eles têm frete grátis só com esse link",
      "Não espere mais, aproveite e clique no link aqui em baixo",
      "Não se arrependa de não ter comprado, é só clicar aqui no link",
      "Se você quiser um ___ igual ao meu, aqui está o link está aqui em baixo, é só clicar",
      "Clique aqui no botão agora para garantir com desconto",
      "Clique aqui no botão mas corre que a promoção é limitada e vai esgotar"
    ],
    "CTA Ambos**": [
      "Pode comprar sem medo sem medo, porque vale muito a pena",
      "Corre lá para o site para garantir o seu",
      "Não tem erro, corre para garantir o seu",
      "Corre para garantir o seu e se surpreender com o resultado",
      "Corre para experimentar e facilitar a sua …..",
      "Experimenta e me conta como funcionou para você",
      "Tome uma atitude hoje e comece hoje a…..",
      "Não sei o que você está esperando para aproveitar esta promoção",
      "Faça um favor a si mesmo e peça seu",
      "Corre para o site deles porque eles estão sempre esgotando",
      "Corre para não perder os descontos",
      "Aproveite que o Dia das Mães está chegando e surpreenda sua mãe",
      "Consegui no site da ____ e me agradeço todos os dias por isso",
      "Faça o teste gratuito no site ____",
      "Me cadastrei aqui e me deram 10% de desconto",
      "Confira a nova coleção em _____",
      "Comprei o meu em ____ e eles têm mil opções",
      "Encomendei nesta página e não tive problemas",
      "Encomendei nesta página e chegou super rápido",
      "Se eu fosse você já começava logo e corria para o site",
      "Antes tarde do que nunca, corre para o site de uma vez para garantir",
      "Você não perde nada verificando se eles ainda o têm no site",
      ". Se você gostou disso, tem que ver o site deles",
      "Melhor reservar de uma vez por todas o seu",
      "Não sei o que você está esperando para colocar ___ no seu carrinho agora",
      "Aqui deixo o link pra vocês para vocês e por falar nisso de nada",
      "Corra para a loja ___ e me agradeça mais tarde",
      "Se esse vídeo apareceu para você, é o seu sinal para comprar ___",
      "Peça porque sempre acaba",
      "Não fique para trás e corre para garantir o seu ___",
      "Confie em mim e garanta os seus de uma vez",
      "Vi que ele só tinha mais uns 3 unidades do ___, então corre para o site",
      "Você tem até ___ para fazer o pedido no site com desconto",
      "Encomende aqui no site que chegará bem rápido",
      "Não perca o seu ___ e peça agora",
      "Não deixe para depois, compre em menos de 1 minuto aqui no site",
      "Peça seu ___, e você vai se lembrar de mim por isso",
      "Por pura sorte ainda está disponível aqui no site",
      "Não quero te assustar, mas restam poucas unidades",
      "Use ___ e me diga qual é a diferença amanhã",
      "Hoje é o seu dia de dizer “eu mereço”, corre para o site",
      ". Eu disse “eu mereço” e encomendei no site",
      "Agora entendi tudo! Corre para o site garantir o seu",
      ". Meu ___ estava certo, eu precisava desse ____ da _____",
      "Aparentemente ainda está à venda, é só corre lá para o site",
      "Você não vai querer perder esses resultados! Corre para o site",
      "Acredite, fiquei tão surpreso quanto você, dá uma olhada no site deles e corre para garantir o seu",
      "você já quer se ver ___, não fique aí sentado e peça seu ___",
      "Se você não acredita, veja você mesmo, peça o seu no site da _____",
      "Adorei como foi fácil comprar os meus lá no site, corre pra garantir os seus também",
      "Chegou no dia seguinte, obrigado por ______ por existirem",
      "Primeira vez que ___ vale a pena, fiz meu pedido lá no site da ______",
      "Core agora para que chegue antes do Natal",
      "Presente perfeito para ___!",
      "Ouso dizer que não existe site melhor",
      "Eles reabastecem o estoque na próxima semana então corre para o site da ____",
      "___ será seu melhor amigo, corre agora para o site",
      "10/10 para ele, corre para o site e depois me conta o que achou"
    ],
    "CTA Orgânico**": [
      "Comenta aqui embaixo que já te envio o link que comprei",
      "Marque alguém que…",
      "Já salva esse vídeo para…",
      "Comente aqui para receber…",
      "Compartilhe com alguém que precisa disso",
      "Não perca as próximas promoções e siga _____",
      "Quer saber mais? Deixa um comentário aqui!",
      "Corre e garante o seu antes que acabe!",
      "Você também amou? Salva pra não esquecer!",
      "Me conta aqui nos comentários o que você achou!",
      "Quer saber onde comprei? Comenta aqui embaixo que eu te conto!",
      "Quer ver mais detalhes? Deixa um ‘eu quero’ nos comentários!",
      "Tá esperando o quê? Vai lá conferir agora!",
      "Gostou da ideia? Comenta e me diz o que achou!",
      "Dúvidas? Deixa aqui nos comentários que eu respondo!",
      "Salva esse vídeo pra lembrar de testar depois!"
    ]
  },
  "formats": [
    "Trend - Queria tanto achar um xxxx que xxx - achou (colocar música trend)",
    "Benefícios e soluções",
    "Respostas a comentário, tik tok",
    "Rotina AM/PM",
    "Mostrando textura - ASMR",
    "Review",
    "Sensorial",
    "X motivos para amar o …",
    "Unboxing",
    "Rotina de skin care com (citar a marca)",
    "3 hábitos que vão salvar sua pele.",
    "Formato 1x1 (conversa com amiga)",
    "Tutorial de como usar",
    "Vlog",
    "Hack de produtos",
    "vídeo demonstrativo",
    "esperiências",
    "Conteúdo salvável estilo gringa",
    "Prova Social (antes e depois)",
    "Formato lista - 5 ocasiões X 5 formas de usar o produto",
    "formato entrevista na rua",
    "Formato Duo",
    "Respostas a comentário"
  ],
  "coreFramework": [
    "Gancho",
    "Problema vivido em primeira pessoa",
    "Solução anterior que falhou, quando fizer sentido",
    "Produto como solução",
    "Benefício e resultado percebido",
    "Educação ou explicação curta",
    "Demonstração prática",
    "Confiança ou prova",
    "Oferta verdadeira",
    "CTA compatível com orgânico ou ADS"
  ]
};
});
